Repository SOPT-32ND-APP2-Myhouse/Myhouse_AOS, pull requests merged in 2023-05, with the labels that each got.

#9 [init] 서버 통신 기초 세팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myhouse_aos/data/ApiFactory.kt
  app/src/main/java/com/example/myhouse_aos/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/com/example/myhouse_aos/presentation/common/ViewModelFactory.kt
  app/src/main/java/com/example/myhouse_aos/presentation/dummy/DummyViewModel.kt
Labels: init, 🐥다은🐥

#4 [feat] 둘러보기 뷰 디자인
  app/src/main/java/com/example/myhouse_aos/domain/model/PostContent.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/ContentAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/FragmentPost.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/HotContentAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/PostViewModel.kt
  app/src/main/res/drawable/backgrond_search.xml
  app/src/main/res/drawable/background_rank.xml
  app/src/main/res/drawable/hot_content.png
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_bookmark_big.xml
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_chip_fancy.xml
  app/src/main/res/drawable/ic_chip_modern.xml
  app/src/main/res/drawable/ic_chip_retro.xml
  app/src/main/res/drawable/ic_chip_simple.xml
  app/src/main/res/drawable/ic_chip_white.xml
  app/src/main/res/drawable/ic_chip_wood.xml
  app/src/main/res/drawable/ic_images.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/post_content.png
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_hot_content.xml
  app/src/main/res/layout/item_post_content.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, 🐥다은🐥

#7 [feat] 콘텐츠 뷰 디자인
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myhouse_aos/domain/model/ContentDetailData.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/HashTagData.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/TodayRecommendData.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/UserBestData.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/UserimageData.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentActivity.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentViewModel.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentDetailAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentHashtagAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentTodayRecommendAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentUserBestAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentUserimageAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/dummy/DummyFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/main/MainActivity.kt
  app/src/main/java/com/example/myhouse_aos/util/snackbar/ScrapSnackbar.kt
  app/src/main/res/drawable/back.xml
  app/src/main/res/drawable/bookmark.xml
  app/src/main/res/drawable/bookmark_clicked.xml
  app/src/main/res/drawable/bookmark_selector.xml
  app/src/main/res/drawable/card3.png
  app/src/main/res/drawable/content_detail_card.png
  app/src/main/res/drawable/edittext_shape.xml
  app/src/main/res/drawable/follow.xml
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/home_selected.xml
  app/src/main/res/drawable/home_selector.xml
  app/src/main/res/drawable/menu_selector_color.xml
  app/src/main/res/drawable/more.xml
  app/src/main/res/drawable/mypage.xml
  app/src/main/res/drawable/profile.png
  app/src/main/res/drawable/round.xml
  app/src/main/res/drawable/round_background.xml
  app/src/main/res/drawable/scrap_button.xml
  app/src/main/res/drawable/scrap_button_clicked.xml
  app/src/main/res/drawable/scrap_button_selector.xml
  app/src/main/res/drawable/shopping.xml
  app/src/main/res/drawable/snackbar_btn_folder.xml
  app/src/main/res/drawable/snackbar_btn_scrapbook.xml
  app/src/main/res/drawable/todayfind.xml
  app/src/main/res/drawable/todayfind_selected.xml
  app/src/main/res/drawable/todayfind_selector.xml
  app/src/main/res/drawable/todayrecommend.png
  app/src/main/res/drawable/userbest.png
  app/src/main/res/drawable/userimage.png
  app/src/main/res/drawable/various.xml
  app/src/main/res/drawable/watch_more.xml
  app/src/main/res/layout/activity_content.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/custom_snackbar.xml
  app/src/main/res/layout/item_content_detail.xml
  app/src/main/res/layout/item_content_hashtag.xml
  app/src/main/res/layout/item_content_today_recommend.xml
  app/src/main/res/layout/item_content_userbest.xml
  app/src/main/res/layout/item_content_userimage.xml
  app/src/main/res/menu/main.xml
  app/src/main/res/values/strings.xml
Labels: feat, 🐯상욱🐯

#8 [Feat] bottomsheet 뷰 구현
  app/src/main/java/com/example/myhouse_aos/presentation/home/BottomSheetDialog.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/btsheet_with_corner.xml
  app/src/main/res/drawable/img_bottom_1.png
  app/src/main/res/drawable/img_bottom_2.png
  app/src/main/res/drawable/img_bottom_3.png
  app/src/main/res/drawable/img_bottom_4.png
  app/src/main/res/drawable/shape.xml
  app/src/main/res/layout/layout_bottom_sheet.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, 🐰혜선🐰

#10 [feat] 화면 연결 및 전체 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentActivity.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentDetailAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentHashtagAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentTodayRecommendAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentUserBestAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentUserimageAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/BottomSheetDialog.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/myhouse_aos/presentation/main/MainActivity.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/ContentAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/PostFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/scrap/ScrapActivity.kt
  app/src/main/java/com/example/myhouse_aos/util/snackbar/ScrapSnackbar.kt
  app/src/main/res/drawable/bookmark.xml
  app/src/main/res/drawable/bookmark_selector.xml
  app/src/main/res/drawable/ic_bookmark_clicked.xml
  app/src/main/res/drawable/ic_market.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/custom_snackbar.xml
  app/src/main/res/layout/layout_bottom_sheet.xml
Labels: feat, 🐥다은🐥

#11 [Mod] 홈 뷰 제약설정 수정
  app/build.gradle
  app/src/main/java/com/example/myhouse_aos/presentation/home/BestAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/PagerFragment.kt
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_photo_ranking.xml
  app/src/main/res/drawable/img_color_interior.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_pager.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_color_interior.xml
  app/src/main/res/layout/item_color_product.xml
  app/src/main/res/layout/item_content_hashtag.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/layout/item_popular_photo.xml
  app/src/main/res/layout/item_recommend_home.xml
  app/src/main/res/layout/item_recommend_product.xml
  app/src/main/res/layout/item_summer_contents.xml
Labels: mod, 🐰혜선🐰

#12 [feat] 스크랩뷰 api 연동
  app/src/main/java/com/example/myhouse_aos/data/ApiFactory.kt
  app/src/main/java/com/example/myhouse_aos/data/datasource/ScrapDatasource.kt
  app/src/main/java/com/example/myhouse_aos/data/model/response/ResponseAllScrap.kt
  app/src/main/java/com/example/myhouse_aos/data/repository/ScrapRepositoryImpl.kt
  app/src/main/java/com/example/myhouse_aos/data/service/ScrapService.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/Folder.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/Scrap.kt
  app/src/main/java/com/example/myhouse_aos/domain/repository/ScrapRepository.kt
  app/src/main/java/com/example/myhouse_aos/presentation/common/ViewModelFactory.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentViewModel.kt
  app/src/main/java/com/example/myhouse_aos/presentation/scrap/FolderAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/scrap/ScrapActivity.kt
  app/src/main/java/com/example/myhouse_aos/presentation/scrap/ScrapAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/scrap/ScrapViewModel.kt
  app/src/main/java/com/example/myhouse_aos/util/binding/ItemBindingAdapte.kt
  app/src/main/res/layout/activity_scrap.xml
  app/src/main/res/layout/item_folder.xml
Labels: feat, 🐥다은🐥

#13 [feat] 둘러보기 뷰 api 연동
  app/src/main/java/com/example/myhouse_aos/data/ApiFactory.kt
  app/src/main/java/com/example/myhouse_aos/data/datasource/PostContentDatasource.kt
  app/src/main/java/com/example/myhouse_aos/data/model/response/ResponsePostContent.kt
  app/src/main/java/com/example/myhouse_aos/data/repository/PostContentRepositoryImpl.kt
  app/src/main/java/com/example/myhouse_aos/data/service/PostService.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/PostContent.kt
  app/src/main/java/com/example/myhouse_aos/domain/repository/PostContentRepository.kt
  app/src/main/java/com/example/myhouse_aos/presentation/common/ViewModelFactory.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/PostFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/post/PostViewModel.kt
  app/src/main/java/com/example/myhouse_aos/util/binding/BindingAdapter.kt
  app/src/main/res/layout/item_hot_content.xml
  app/src/main/res/layout/item_post_content.xml
Labels: feat, 🐥다은🐥

#14 [Feat] 홈 뷰 api 연동
  app/src/main/java/com/example/myhouse_aos/data/ApiFactory.kt
  app/src/main/java/com/example/myhouse_aos/data/datasource/GetBestProductDataSource.kt
  app/src/main/java/com/example/myhouse_aos/data/datasource/GetPopularContentsDataSource.kt
  app/src/main/java/com/example/myhouse_aos/data/datasource/GetRecommendHomeDataSource.kt
  app/src/main/java/com/example/myhouse_aos/data/model/response/ResponseBestProduct.kt
  app/src/main/java/com/example/myhouse_aos/data/model/response/ResponsePopularContent.kt
  app/src/main/java/com/example/myhouse_aos/data/model/response/ResponseRecommendHome.kt
  app/src/main/java/com/example/myhouse_aos/data/repository/GetBestProductRepositoryImpl.kt
  app/src/main/java/com/example/myhouse_aos/data/repository/GetPopularContentsRespositoryImpl.kt
  app/src/main/java/com/example/myhouse_aos/data/repository/GetRecommendHomeRepositoryImpl.kt
  app/src/main/java/com/example/myhouse_aos/data/service/AuthState.kt
  app/src/main/java/com/example/myhouse_aos/data/service/GetService.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/BestProductModel.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/PopularContentsModel.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/RecommendHomeModel.kt
  app/src/main/java/com/example/myhouse_aos/domain/repository/GetBestProductRepository.kt
  app/src/main/java/com/example/myhouse_aos/domain/repository/GetPopularContentsRepository.kt
  app/src/main/java/com/example/myhouse_aos/domain/repository/GetRecommendHomeRepository.kt
  app/src/main/java/com/example/myhouse_aos/presentation/common/ViewModelFactory.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/PagerFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/PopularContentsAdapter.kt
  app/src/main/java/com/example/myhouse_aos/util/binding/ItemBindingAdapte.kt
  app/src/main/res/layout/fragment_pager.xml
  app/src/main/res/layout/item_color_product.xml
  app/src/main/res/layout/item_popular_contents.xml
  app/src/main/res/layout/item_popular_photo.xml
  app/src/main/res/layout/item_recommend_home.xml
  app/src/main/res/layout/item_recommend_product.xml
  app/src/main/res/values/strings.xml
Labels: feat, 🐰혜선🐰

#16 [mod] 전체 로직, 뷰 수정
  app/src/main/java/com/example/myhouse_aos/data/datasource/DummyDatasource.kt
  app/src/main/java/com/example/myhouse_aos/data/model/request/RequestData.kt
  app/src/main/java/com/example/myhouse_aos/data/model/response/ResponseData.kt
  app/src/main/java/com/example/myhouse_aos/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/com/example/myhouse_aos/data/service/DummyService.kt
  app/src/main/java/com/example/myhouse_aos/domain/model/DummyData.kt
  app/src/main/java/com/example/myhouse_aos/domain/repository/DummyRepository.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentActivity.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentViewModel.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentDetailAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentTodayRecommendAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentUserBestAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/dummy/DummyActivity.kt
  app/src/main/java/com/example/myhouse_aos/presentation/dummy/DummyFragment.kt
  app/src/main/java/com/example/myhouse_aos/presentation/dummy/DummyViewModel.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/BottomSheetDialog.kt
  app/src/main/java/com/example/myhouse_aos/util/binding/BindingAdapter.kt
  app/src/main/java/com/example/myhouse_aos/util/binding/ItemBindingAdapter.kt
  app/src/main/res/layout/activity_content.xml
  app/src/main/res/layout/activity_dummy.xml
  app/src/main/res/layout/fragment_dummy.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recommend_home.xml
  app/src/main/res/layout/layout_bottom_sheet.xml
  app/src/main/res/values/strings.xml
Labels: mod, 🐥다은🐥

#17 [mod] contentview 로직 수정, contentview 수정
  README.md
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentActivity.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/ContentViewModel.kt
  app/src/main/java/com/example/myhouse_aos/presentation/content/adapter/ItemContentDetailAdapter.kt
  app/src/main/java/com/example/myhouse_aos/presentation/home/BottomSheetDialog.kt
Labels: mod, 🐯상욱🐯
